config/routes.rb
Rails.application.routes.draw do
  resources :candidates

  root 'candidates#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_one_attached :avatar

  validates_presence_of :name
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP, presence: true
  validates_format_of :phone, :with => /\w/, allow_blank: true
  validates_inclusion_of :career_level, in: ['Student', 'Graduate', 'Entry Level', 'Experienced', 'Executive', 'Senior Executive'],
                         message: "%{value} is not a valid career level"
  validates_numericality_of :years_of_experience, only_integer: true, allow_blank: true
  validates_length_of :cover_note, maximum: 200, allow_blank: true
  validates_format_of :avatar_attachment, :with => /\.(jpeg|jpg|png|gif)$/i, :multiline => true, allow_blank: true
  validate :validate_skills

  private

  def validate_skills
    errors.add(:skills, 'are less than 3') unless skills.reject {|e| e.to_s.empty?}.length >= 3
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      redirect_to @candidate
    else
      render 'new'
    end
  end

  def show
    @candidate = Candidate.find(params[:id])
  end


  private

  def candidate_params
    params.require(:candidate).permit(:name, :email, :phone, :career_level, :years_of_experience, :cover_note, :avatar, skills: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/new.html.erb
<div class="container">
  <h4 class="font-weight-bold py-3 mb-4">DQ Media Test</h4>

  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
        <% @candidate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with scope: :candidate, url: candidates_path, multipart: true, local: true do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :phone %>
      <%= form.text_field :phone, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :career_level %>
      <%= form.select :career_level, options_for_select(['Student',
                                                         'Graduate',
                                                         'Entry Level',
                                                         'Experienced',
                                                         'Executive',
                                                         'Senior Executive']), {}, {:class => "form-control"} %>
    </div>
    <div class="form-group">
      <%= form.label :years_of_experience %>
      <%= form.number_field(:years_of_experience, step: 1, :class => 'form-control') %>
    </div>
    <div class="form-group">
      <%= form.label :cover_note %>
      <%= form.text_field :cover_note, :class => "form-control", :max => 200 %>
    </div>
    <div class="form-group">
      <div class="custom-file">
        <%= form.file_field :avatar, :class => "custom-file-input", :accept => 'image/x-png,image/gif,image/jpeg' %>
        <%= form.label :avatar, :class => "custom-file-label" %>
      </div>
    </div>
    <div class="form-group">
      <div class="d-flex">
        <label for="candidate[skills[]]">Skills</label>
        <a href="javascript:void(0)" class="btn btn-sm btn-primary ml-auto" onclick="addSingleElement('data-skills-container', '#new-skills')">Add Skill</a>
      </div>
    </div>
    <% (1..3).each do |i| %>
    <div data-skills-container="<%= i %>">
      <div class="form-group">
        <input type="text" name="candidate[skills][]" class="form-control" placeholder="Skill">
      </div>
      <div class="text-right">
        <a href="javascript:void(0)" class="text-danger text-small"
           onclick="removeElement($(this), 'data-skills-container')">Remove</a>
      </div>
    </div>
    <% end %>
    <div id="new-skills"></div>


    <div class="form-group">
      <%= form.submit :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

<script type="text/javascript">

    function addSingleElement(identifier, placeholder) {
        if ($('[' + identifier + '].d-none').length === 1) {
            $('[' + identifier + ']').removeClass('d-none');
            return false;
        }
        var $last = $('[' + identifier + ']').last();
        var $newElement = $last.clone();
        $newElement.find('input').val(null);
        $newElement.insertBefore($(placeholder));
        return false;
    }

    function removeElement(element, identifier) {
        if ($('[' + identifier + ']').length > 3) {
            $(element).parent('div').parent('div').remove();
        }
    }
</script>

app/views/candidates/show.html.erb
<div class="container">
  <h4 class="font-weight-bold py-3 mb-4">DQ Media Test</h4>
  <dl class="row">
    <dt class="col-sm-3">Name:</dt>
    <dd class="col-sm-9"><%= @candidate.name %></dd>
    <dt class="col-sm-3">Avatar:</dt>
    <dd class="col-sm-9">
      <% if @candidate.avatar.attached? %>
        <%= image_tag @candidate.avatar , :class => "img-thumbnail"%>
      <% else %>
        <em>No avatar</em>
      <% end %>
    </dd>
    <dt class="col-sm-3">Skills:</dt>
    <dd class="col-sm-9"><%= @candidate.skills %></dd>
    <dt class="col-sm-3">Email:</dt>
    <dd class="col-sm-9"><%= @candidate.email %></dd>
    <dt class="col-sm-3">Experience:</dt>
    <dd class="col-sm-9"><%= @candidate.years_of_experience %> years</dd>
    <dt class="col-sm-3">Phone:</dt>
    <dd class="col-sm-9"><%= @candidate.phone %></dd>
    <dt class="col-sm-3">Career level:</dt>
    <dd class="col-sm-9"><%= @candidate.career_level %></dd>
    <dt class="col-sm-3">Cover note:</dt>
    <dd class="col-sm-9"><%= @candidate.cover_note %></dd>
  </dl>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DQ Media Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Main font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900" rel="stylesheet">

    <%= stylesheet_link_tag 'bootstrap.css', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Libs -->
    <!-- Core scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'bootstrap.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>